import { useEffect, useMemo, useState } from 'react'
import { Archive, ArrowUpRight, CalendarDays, Check, ChevronDown, Circle, Clock3, ListFilter, LoaderCircle, Plus, Search, Sparkles, Tag, Trash2, WandSparkles, X } from 'lucide-react'
import * as api from './api/client.js'

const initialForm = { title: '', description: '', dueDate: '', priority: 'medium', tags: [] }
const priorityMeta = { high: { label: 'High', className: 'priority-high' }, medium: { label: 'Medium', className: 'priority-medium' }, low: { label: 'Low', className: 'priority-low' } }

function App() {
  const [tasks, setTasks] = useState([])
  const [form, setForm] = useState(initialForm)
  const [smartText, setSmartText] = useState('')
  const [filter, setFilter] = useState('all')
  const [search, setSearch] = useState('')
  const [summary, setSummary] = useState('')
  const [breakdownTask, setBreakdownTask] = useState(null)
  const [loading, setLoading] = useState({ tasks: true, smart: false, summary: false, breakdown: false })
  const [error, setError] = useState('')

  const loadTasks = async (query = '') => { setLoading((state) => ({ ...state, tasks: true })); try { setTasks((await api.getTasks(query)).tasks) } catch (err) { setError(err.message) } finally { setLoading((state) => ({ ...state, tasks: false })) } }
  useEffect(() => { loadTasks() }, [])

  const visibleTasks = useMemo(() => filter === 'all' ? tasks : tasks.filter((task) => filter === 'completed' ? task.status === 'completed' : task.status === 'pending'), [tasks, filter])
  const doneCount = tasks.filter((task) => task.status === 'completed').length
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })

  async function submitTask(event) { event.preventDefault(); if (!form.title.trim()) return setError('Give your task a title first.'); try { const result = await api.createTask(form); setTasks((current) => [result.task, ...current]); setForm(initialForm); setError('') } catch (err) { setError(err.message) } }
  async function smartCreate() { if (!smartText.trim()) return; setLoading((state) => ({ ...state, smart: true })); try { const result = await api.parseTask(smartText); setForm({ ...initialForm, ...result.task }); setSmartText(''); setError(result.fallback ? 'AI is offline, so the sentence was parsed with local rules. Review the fields before saving.' : '') } catch (err) { setError(err.message) } finally { setLoading((state) => ({ ...state, smart: false })) } }
  async function toggleTask(task) { try { const result = await api.setTaskStatus(task.id, task.status === 'completed' ? 'pending' : 'completed'); setTasks((current) => current.map((item) => item.id === task.id ? result.task : item)) } catch (err) { setError(err.message) } }
  async function deleteTask(id) { try { await api.removeTask(id); setTasks((current) => current.filter((task) => task.id !== id)) } catch (err) { setError(err.message) } }
  async function doSearch(event) { event.preventDefault(); if (!search.trim()) return loadTasks(); try { setTasks((await api.smartSearch(search)).tasks); setError('') } catch (err) { setError(err.message) } }
  async function getSummary() { setLoading((state) => ({ ...state, summary: true })); try { setSummary((await api.dailySummary()).summary) } catch (err) { setError(err.message) } finally { setLoading((state) => ({ ...state, summary: false })) } }
  async function getBreakdown(task) { setBreakdownTask({ ...task, subtasks: null }); setLoading((state) => ({ ...state, breakdown: true })); try { setBreakdownTask({ ...task, subtasks: (await api.breakdown(task)).subtasks }) } catch (err) { setError(err.message); setBreakdownTask(null) } finally { setLoading((state) => ({ ...state, breakdown: false })) } }

  return <div className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark"><Check size={18} strokeWidth={3} /></span><span>daymark</span></div><div className="date-stamp"><CalendarDays size={16} /> {today}</div><button className="avatar" title="Account">RM</button></header>
    <main className="workspace">
      <section className="intro"><div><p className="eyebrow">Your day, in focus</p><h1>Make room for<br /><em>what matters.</em></h1></div><div className="progress-wrap"><div className="progress-copy"><span>Daily progress</span><strong>{doneCount} / {tasks.length || 0}</strong></div><div className="progress-track"><span style={{ width: `${tasks.length ? doneCount / tasks.length * 100 : 0}%` }} /></div></div></section>
      {error && <div className="notice"><Sparkles size={16} /><span>{error}</span><button onClick={() => setError('')}><X size={15} /></button></div>}
      <section className="smart-panel"><div className="smart-icon"><WandSparkles size={22} /></div><div className="smart-copy"><div className="panel-kicker">AI-assisted capture</div><h2>What's on your mind?</h2><p>Tell me naturally and I'll shape it into a task.</p></div><div className="smart-input"><input value={smartText} onChange={(event) => setSmartText(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && smartCreate()} placeholder="e.g. Plan a team offsite next Friday, high priority" /><button onClick={smartCreate} disabled={loading.smart || !smartText.trim()}>{loading.smart ? <LoaderCircle className="spin" size={18} /> : <ArrowUpRight size={18} />}</button></div></section>
      <div className="content-grid"><section className="tasks-column"><div className="section-heading"><div><p className="eyebrow">The list</p><h2>Today's tasks</h2></div><button className="icon-button" onClick={() => loadTasks()} title="Refresh tasks"><Archive size={18} /></button></div><div className="toolbar"><div className="tabs">{[['all', 'All'], ['pending', 'To do'], ['completed', 'Done']].map(([value, label]) => <button className={filter === value ? 'active' : ''} onClick={() => setFilter(value)} key={value}>{label}<span>{value === 'all' ? tasks.length : tasks.filter((task) => task.status === (value === 'completed' ? 'completed' : 'pending')).length}</span></button>)}</div><form className="search" onSubmit={doSearch}><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search naturally..." /><button title="Search"><ArrowUpRight size={16} /></button></form></div><div className="task-list">{loading.tasks ? <div className="empty-state"><LoaderCircle className="spin" /> Loading your tasks...</div> : visibleTasks.length ? visibleTasks.map((task) => <TaskRow key={task.id} task={task} onToggle={toggleTask} onDelete={deleteTask} onBreakdown={getBreakdown} />) : <div className="empty-state"><Circle size={20} /><span>No tasks here yet.</span></div>}</div></section><aside className="side-column"><div className="form-card"><div className="section-heading compact"><div><p className="eyebrow">New entry</p><h2>Add a task</h2></div><Plus size={20} /></div><form onSubmit={submitTask}><input className="field-title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Task title" /><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="A little context (optional)" rows="3" /><div className="field-row"><label><span>Due date</span><input type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /></label><label><span>Priority</span><select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}>{Object.entries(priorityMeta).map(([key, item]) => <option key={key} value={key}>{item.label}</option>)}</select></label></div><button className="primary-button" type="submit"><Plus size={17} /> Add to list</button></form></div><div className="summary-card"><div className="summary-top"><div className="summary-icon"><Sparkles size={18} /></div><span>Daily reflection</span></div>{summary ? <p>{summary}</p> : <p className="muted">A small view of what needs your attention today.</p>}<button className="text-button" onClick={getSummary} disabled={loading.summary}>{loading.summary ? <LoaderCircle className="spin" size={15} /> : <Sparkles size={15} />} {summary ? 'Refresh summary' : 'Generate summary'}</button></div></aside></div>
    </main>
    {breakdownTask && <div className="modal-backdrop" onClick={() => setBreakdownTask(null)}><div className="modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setBreakdownTask(null)}><X size={18} /></button><p className="eyebrow">AI task breakdown</p><h2>{breakdownTask.title}</h2>{loading.breakdown ? <div className="loading-line"><LoaderCircle className="spin" size={18} /> Thinking through the next steps...</div> : <ol>{breakdownTask.subtasks?.map((subtask) => <li key={subtask}><span><Check size={14} /></span>{subtask}</li>)}</ol>}</div></div>}
  </div>
}

function TaskRow({ task, onToggle, onDelete, onBreakdown }) { const overdue = task.status === 'pending' && task.due_date && task.due_date < new Date().toISOString().slice(0, 10); return <article className={`task-row ${task.status === 'completed' ? 'is-done' : ''}`}><button className="check-button" onClick={() => onToggle(task)} title={task.status === 'completed' ? 'Mark incomplete' : 'Mark complete'}>{task.status === 'completed' ? <Check size={15} /> : <Circle size={19} />}</button><div className="task-main"><div className="task-title-line"><h3>{task.title}</h3><span className={`priority-dot ${priorityMeta[task.priority].className}`} title={`${priorityMeta[task.priority].label} priority`} /></div>{task.description && <p>{task.description}</p>}<div className="task-meta">{task.due_date && <span className={overdue ? 'overdue' : ''}><Clock3 size={13} /> {overdue ? 'Overdue' : new Date(`${task.due_date}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span>}{task.tags?.map((tag) => <span key={tag}><Tag size={12} /> {tag}</span>)}</div></div><div className="task-actions"><button onClick={() => onBreakdown(task)} title="Break down with AI"><WandSparkles size={16} /></button><button onClick={() => onDelete(task.id)} title="Delete task"><Trash2 size={16} /></button></div></article> }

export default App
